name: Build & Push MLflow Image
on:
  workflow_dispatch:
  push:
    paths:
      - docker/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/weirichd/mlflow-server:latest

