name: Deploy Infra (MLflow SQLite)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-2

      - name: Clear failed stack if present
        run: |
            set -euo pipefail
            STACK="mlflow-sqlite"
            STATUS=$(aws cloudformation describe-stacks \
            --stack-name "$STACK" \
            --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "NOTFOUND")
            echo "Current stack status: $STATUS"
            if [ "$STATUS" = "ROLLBACK_COMPLETE" ] || [ "$STATUS" = "CREATE_FAILED" ] || [ "$STATUS" = "ROLLBACK_FAILED" ]; then
            aws cloudformation delete-stack --stack-name "$STACK"
            aws cloudformation wait stack-delete-complete --stack-name "$STACK"
            echo "Deleted $STACK. Proceeding with fresh deploy."
            fi


      - name: Deploy CloudFormation stack
        run: |
            set -euo pipefail

            # Discover default VPC and a default subnet in us-east-2
            VPC_ID=$(aws ec2 describe-vpcs \
            --filters Name=isDefault,Values=true \
            --query 'Vpcs[0].VpcId' --output text)

            SUBNET_ID=$(aws ec2 describe-subnets \
            --filters Name=vpc-id,Values=${VPC_ID} Name=default-for-az,Values=true \
            --query 'Subnets[0].SubnetId' --output text)

            # Fetch Ubuntu 22.04 (Jammy) AMI
            UBUNTU_AMI=$(aws ec2 describe-images \
            --owners 099720109477 \
            --filters \
                "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
                "Name=state,Values=available" \
                "Name=virtualization-type,Values=hvm" \
                "Name=architecture,Values=x86_64" \
            --query 'reverse(sort_by(Images, &CreationDate))[0].ImageId' \
            --output text)

            echo "VPC_ID=${VPC_ID}"
            echo "SUBNET_ID=${SUBNET_ID}"
            echo "UBUNTU_AMI=${UBUNTU_AMI}"

            aws cloudformation deploy \
            --template-file cloudformation/mlflow-sqlite.yaml \
            --stack-name mlflow-sqlite \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                Env=prod \
                KeyPairName='${{ secrets.EC2_KEYPAIR_NAME }}' \
                SSHCidr='${{ secrets.SSH_CIDR }}' \
                DockerImage='${{ vars.DOCKER_IMAGE }}' \
                VpcId="${VPC_ID}" \
                SubnetId="${SUBNET_ID}" \
                UbuntuAmiId="${UBUNTU_AMI}"

      - name: Collect server logs via SSM
        if: always()
        run: |
          set -euo pipefail

          # Find the instance by CFN stack + tag
          IID=$(aws ec2 describe-instances \
            --filters "Name=tag:aws:cloudformation:stack-name,Values=mlflow-sqlite" "Name=instance-state-name,Values=running" \
            --query 'Reservations[0].Instances[0].InstanceId' --output text)

          echo "InstanceId=$IID"

          # Ask SSM to run a few diagnostics
          CMD_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "$IID" \
            --parameters commands="$(
              cat <<'EOS'
              set -eux
              systemctl status mlflow --no-pager --lines=30 || true
              journalctl -u mlflow -n 120 --no-pager || true
              docker ps -a || true
              cat /etc/mlflow/env || true
              ls -ld /var/lib/mlflow/db /var/lib/mlflow/auth || true
              ls -l /var/lib/mlflow/auth || true
              tail -n 80 /var/log/nginx/error.log || true
              curl -sI http://127.0.0.1:5000 | head -n1 || true
              EOS
            )" \
            --query 'Command.CommandId' --output text)

          # Wait and print
          aws ssm wait command-executed --command-id "$CMD_ID" --instance-id "$IID"
          aws ssm get-command-invocation --command-id "$CMD_ID" --instance-id "$IID" \
            --query '[Status,StandardOutputContent,StandardErrorContent]' --output text


      - name: Show stack outputs
        run: |
          aws cloudformation describe-stacks --stack-name mlflow-sqlite \
            --query "Stacks[0].Outputs" --output table

